### ISSUE TITLE
Update the library for Oxford v2

### ISSUE THREAD

**Issue by shaked6540** [witoong623/OxfordDictionariesAPI#2]
The v1 API is going obsolete soon and it will no longer work, meaning this library won't work

more info here https://developer.oxforddictionaries.com/version2

**Comment by witoong623** [comment]
Thank you for reminding me, I will try to update it next weekend.  However, since oxford update it to v2, I also want to structure the API again, which make it incompatibility with v1 of this library.

**Comment by shaked6540** [comment]
I already built the base model structure myself, it's not very different from the current one except a few properties that were changed from a single string to an object

I'll see if I have time this weekend and make a pull request to match it with your project

**Comment by witoong623** [comment]
I'm working on it right now, the responses don't change so much, so I'm writing deserializer myself to provider compatibility with previous version.

**Comment by witoong623** [comment]
and it done https://github.com/witoong623/OxfordDictionariesAPI/releases/tag/v2.0.0

**Comment by shaked6540** [comment]
Nice, thanks
